package com.jkrm.education.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jkrm.education.bean.DaoMarkCommonScoreUseBean;

import com.jkrm.education.db.greendao.DaoMarkCommonScoreUseBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoMarkCommonScoreUseBeanDaoConfig;

    private final DaoMarkCommonScoreUseBeanDao daoMarkCommonScoreUseBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoMarkCommonScoreUseBeanDaoConfig = daoConfigMap.get(DaoMarkCommonScoreUseBeanDao.class).clone();
        daoMarkCommonScoreUseBeanDaoConfig.initIdentityScope(type);

        daoMarkCommonScoreUseBeanDao = new DaoMarkCommonScoreUseBeanDao(daoMarkCommonScoreUseBeanDaoConfig, this);

        registerDao(DaoMarkCommonScoreUseBean.class, daoMarkCommonScoreUseBeanDao);
    }
    
    public void clear() {
        daoMarkCommonScoreUseBeanDaoConfig.clearIdentityScope();
    }

    public DaoMarkCommonScoreUseBeanDao getDaoMarkCommonScoreUseBeanDao() {
        return daoMarkCommonScoreUseBeanDao;
    }

}
