package com.jkrm.education.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jkrm.education.db.DaoCatalogueBean;
import com.jkrm.education.db.DaoVideoBean;
import com.jkrm.education.db.DaoMicroLessonBean;

import com.jkrm.education.db.greendao.DaoCatalogueBeanDao;
import com.jkrm.education.db.greendao.DaoVideoBeanDao;
import com.jkrm.education.db.greendao.DaoMicroLessonBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoCatalogueBeanDaoConfig;
    private final DaoConfig daoVideoBeanDaoConfig;
    private final DaoConfig daoMicroLessonBeanDaoConfig;

    private final DaoCatalogueBeanDao daoCatalogueBeanDao;
    private final DaoVideoBeanDao daoVideoBeanDao;
    private final DaoMicroLessonBeanDao daoMicroLessonBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoCatalogueBeanDaoConfig = daoConfigMap.get(DaoCatalogueBeanDao.class).clone();
        daoCatalogueBeanDaoConfig.initIdentityScope(type);

        daoVideoBeanDaoConfig = daoConfigMap.get(DaoVideoBeanDao.class).clone();
        daoVideoBeanDaoConfig.initIdentityScope(type);

        daoMicroLessonBeanDaoConfig = daoConfigMap.get(DaoMicroLessonBeanDao.class).clone();
        daoMicroLessonBeanDaoConfig.initIdentityScope(type);

        daoCatalogueBeanDao = new DaoCatalogueBeanDao(daoCatalogueBeanDaoConfig, this);
        daoVideoBeanDao = new DaoVideoBeanDao(daoVideoBeanDaoConfig, this);
        daoMicroLessonBeanDao = new DaoMicroLessonBeanDao(daoMicroLessonBeanDaoConfig, this);

        registerDao(DaoCatalogueBean.class, daoCatalogueBeanDao);
        registerDao(DaoVideoBean.class, daoVideoBeanDao);
        registerDao(DaoMicroLessonBean.class, daoMicroLessonBeanDao);
    }
    
    public void clear() {
        daoCatalogueBeanDaoConfig.clearIdentityScope();
        daoVideoBeanDaoConfig.clearIdentityScope();
        daoMicroLessonBeanDaoConfig.clearIdentityScope();
    }

    public DaoCatalogueBeanDao getDaoCatalogueBeanDao() {
        return daoCatalogueBeanDao;
    }

    public DaoVideoBeanDao getDaoVideoBeanDao() {
        return daoVideoBeanDao;
    }

    public DaoMicroLessonBeanDao getDaoMicroLessonBeanDao() {
        return daoMicroLessonBeanDao;
    }

}
